export default {
  GET_LEADS_LIST_START: 'GET_LEADS_LIST_START',
	GET_LEADS_LIST_SUCCESS: 'GET_LEADS_LIST_SUCCESS',
	GET_LEADS_LIST_FAIL: 'GET_LEADS_LIST_FAIL',
	GET_EXTRA_LEADS_LIST_START: 'GET_EXTRA_LEADS_LIST_START',
	GET_EXTRA_LEADS_LIST_SUCCESS: 'GET_EXTRA_LEADS_LIST_SUCCESS',
	GET_EXTRA_LEADS_LIST_FAIL: 'GET_EXTRA_LEADS_LIST_FAIL',
	POST_EXTRA_LEADS_START: 'POST_EXTRA_LEADS_START',
	POST_EXTRA_LEADS_SUCCESS: 'POST_EXTRA_LEADS_SUCCESS',
	POST_EXTRA_LEADS_FAIL: 'POST_EXTRA_LEADS_FAIL',
};
