export default {
  GET_CAMPAIGN_LIST_START: 'GET_CAMPAIGN_LIST_START',
  GET_CAMPAIGN_LIST_SUCCESS: 'GET_CAMPAIGN_LIST_SUCCESS',
  GET_CAMPAIGN_LIST_FAIL: 'GET_CAMPAIGN_LIST_FAIL',
  SET_SELECTED_CAMPAIGN: 'SET_SELECTED_CAMPAIGN',
  SELECTED_CAMPAIGN_KEY: 'SELECTED_CAMPAIGN_KEY',
};
